cache:
  paths:
    - .cache/pip

stages:
  - build
  - deploy


default:
  image: python:3.10-slim
  before_script:
    - mkdir -p .cache/pip
    - python3.10 -m venv venv
    - source venv/bin/activate
    - pip install wheel twine build


build_postal_py:
  stage: build
  rules:
    - changes:
        - postal_py/**/*
      if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"'
  script:
    - python3.10 -m build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 hour


publish_postal_py:
  stage: deploy
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - pyproject.toml
  script:
    - twine upload -u __token__ -p "$PYPI_TOKEN" dist/*
  needs: ["build_postal_py"]